version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: comerciocais-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comerciocais_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
  
volumes:
  postgres_data: